### ISSUE TITLE
支持webpack引入

### ISSUE THREAD

**Issue by LeuisKen** [ichord/simditor-dropzone#4]
希望能够在基于webpack的项目中，使用该插件，目前插件代码中使用的`Simditor`是从全局拿来的，作为对于webpack的包引入时，`Simditor`会是`undefined`。

希望的引入方式：

```
import Simditor from 'simditor'
import 'simditor-dropzone'
```

**Comment by JasinYip** [comment]
请问这个有消息吗？这非常重要啊……

**Comment by ichord** [comment]
已经合并相关 PR 并发布了新版本.

**Comment by JasinYip** [comment]
看样子 npm package 好像还没发布？

**Comment by ichord** [comment]
npm package 的权限不在我这....我去要回来..
